
import os
import time

os.system("qsub fmri_prep_1")
time.sleep(10 * 60)
time.sleep(30)
os.system("qsub fmri_prep_2")
time.sleep(30)
os.system("qsub fmri_prep_3")
time.sleep(30)
os.system("qsub fmri_prep_4")
time.sleep(30)
os.system("qsub fmri_prep_5")
time.sleep(30)
os.system("qsub fmri_prep_6")
time.sleep(30)
os.system("qsub fmri_prep_7")
time.sleep(30)
os.system("qsub fmri_prep_8")
time.sleep(30)
os.system("qsub fmri_prep_9")
time.sleep(30)
os.system("qsub fmri_prep_10")
time.sleep(30)
os.system("qsub fmri_prep_11")
time.sleep(30)
os.system("qsub fmri_prep_12")
time.sleep(30)
os.system("qsub fmri_prep_13")
time.sleep(30)
os.system("qsub fmri_prep_14")
time.sleep(30)
os.system("qsub fmri_prep_15")
time.sleep(30)
os.system("qsub fmri_prep_16")
time.sleep(30)
os.system("qsub fmri_prep_17")
time.sleep(30)
os.system("qsub fmri_prep_18")
time.sleep(30)
os.system("qsub fmri_prep_19")
time.sleep(30)
os.system("qsub fmri_prep_20")
time.sleep(30)
os.system("qsub fmri_prep_21")
time.sleep(30)
os.system("qsub fmri_prep_22")
time.sleep(30)
os.system("qsub fmri_prep_23")
time.sleep(30)
os.system("qsub fmri_prep_24")
time.sleep(30)
os.system("qsub fmri_prep_25")
time.sleep(30)
os.system("qsub fmri_prep_26")
time.sleep(30)
os.system("qsub fmri_prep_27")
time.sleep(30)
os.system("qsub fmri_prep_28")
time.sleep(30)
os.system("qsub fmri_prep_29")
time.sleep(30)
os.system("qsub fmri_prep_30")
time.sleep(30)
os.system("qsub fmri_prep_31")
time.sleep(30)
os.system("qsub fmri_prep_32")
time.sleep(30)
os.system("qsub fmri_prep_33")
time.sleep(30)
os.system("qsub fmri_prep_34")
time.sleep(30)
os.system("qsub fmri_prep_35")
time.sleep(30)
os.system("qsub fmri_prep_36")
time.sleep(30)
os.system("qsub fmri_prep_37")
time.sleep(30)
os.system("qsub fmri_prep_38")
time.sleep(30)
os.system("qsub fmri_prep_39")
time.sleep(30)
os.system("qsub fmri_prep_40")
time.sleep(30)
os.system("qsub fmri_prep_41")
time.sleep(30)
os.system("qsub fmri_prep_42")
time.sleep(30)
os.system("qsub fmri_prep_43")
time.sleep(30)
os.system("qsub fmri_prep_44")
time.sleep(30)
os.system("qsub fmri_prep_45")
time.sleep(30)
os.system("qsub fmri_prep_46")
time.sleep(30)
os.system("qsub fmri_prep_47")
time.sleep(30)
os.system("qsub fmri_prep_48")
time.sleep(30)
os.system("qsub fmri_prep_49")
time.sleep(30)
os.system("qsub fmri_prep_50")
time.sleep(30)
os.system("qsub fmri_prep_51")
time.sleep(30)
os.system("qsub fmri_prep_52")
time.sleep(30)
os.system("qsub fmri_prep_53")
time.sleep(30)
os.system("qsub fmri_prep_54")
