
import os
import time

os.system("qsub highpass_filter_1")
time.sleep(30)
os.system("qsub highpass_filter_2")
time.sleep(30)
os.system("qsub highpass_filter_3")
time.sleep(30)
os.system("qsub highpass_filter_4")
time.sleep(30)
os.system("qsub highpass_filter_5")
time.sleep(30)
os.system("qsub highpass_filter_6")
time.sleep(30)
os.system("qsub highpass_filter_7")
time.sleep(30)
os.system("qsub highpass_filter_8")
time.sleep(30)
os.system("qsub highpass_filter_9")
time.sleep(30)
os.system("qsub highpass_filter_10")
time.sleep(30)
os.system("qsub highpass_filter_11")
time.sleep(30)
os.system("qsub highpass_filter_12")
time.sleep(30)
os.system("qsub highpass_filter_13")
time.sleep(30)
os.system("qsub highpass_filter_14")
time.sleep(30)
os.system("qsub highpass_filter_15")
time.sleep(30)
os.system("qsub highpass_filter_16")
time.sleep(30)
os.system("qsub highpass_filter_17")
time.sleep(30)
os.system("qsub highpass_filter_18")
time.sleep(30)
os.system("qsub highpass_filter_19")
time.sleep(30)
os.system("qsub highpass_filter_20")
time.sleep(30)
os.system("qsub highpass_filter_21")
time.sleep(30)
os.system("qsub highpass_filter_22")
time.sleep(30)
os.system("qsub highpass_filter_23")
time.sleep(30)
os.system("qsub highpass_filter_24")
time.sleep(30)
os.system("qsub highpass_filter_25")
time.sleep(30)
os.system("qsub highpass_filter_26")
time.sleep(30)
os.system("qsub highpass_filter_27")
time.sleep(30)
os.system("qsub highpass_filter_28")
time.sleep(30)
os.system("qsub highpass_filter_29")
time.sleep(30)
os.system("qsub highpass_filter_30")
time.sleep(30)
os.system("qsub highpass_filter_31")
time.sleep(30)
os.system("qsub highpass_filter_32")
time.sleep(30)
os.system("qsub highpass_filter_33")
time.sleep(30)
os.system("qsub highpass_filter_34")
time.sleep(30)
os.system("qsub highpass_filter_35")
time.sleep(30)
os.system("qsub highpass_filter_36")
time.sleep(30)
os.system("qsub highpass_filter_37")
time.sleep(30)
os.system("qsub highpass_filter_38")
time.sleep(30)
os.system("qsub highpass_filter_39")
time.sleep(30)
os.system("qsub highpass_filter_40")
time.sleep(30)
os.system("qsub highpass_filter_41")
time.sleep(30)
os.system("qsub highpass_filter_42")
time.sleep(30)
os.system("qsub highpass_filter_43")
time.sleep(30)
os.system("qsub highpass_filter_44")
time.sleep(30)
os.system("qsub highpass_filter_45")
time.sleep(30)
os.system("qsub highpass_filter_46")
time.sleep(30)
os.system("qsub highpass_filter_47")
time.sleep(30)
os.system("qsub highpass_filter_48")
time.sleep(30)
os.system("qsub highpass_filter_49")
time.sleep(30)
os.system("qsub highpass_filter_50")
time.sleep(30)
os.system("qsub highpass_filter_51")
time.sleep(30)
os.system("qsub highpass_filter_52")
time.sleep(30)
os.system("qsub highpass_filter_53")
time.sleep(30)
os.system("qsub highpass_filter_54")
